// flow-typed signature: ff44f6a225a69bcb3f4a4443e3c5ce10
// flow-typed version: <<STUB>>/ovrui_v~1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ovrui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ovrui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ovrui/dist/ovrui' {
  declare module.exports: any;
}

declare module 'ovrui/dist/ovrui.min' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Control/AppControls' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Control/DeviceOrientationControls' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Control/MousePanControls' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Control/VRControls' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Control/VREffect' {
  declare module.exports: any;
}

declare module 'ovrui/lib/FourByFourRect/VectorGeometry' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Inputs/__tests__/GamepadEventInput-test' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Inputs/EventInput' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Inputs/GamepadEventInput' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Inputs/KeyboardEventInput' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Inputs/MouseEventInput' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Inputs/MouseRayCaster' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Inputs/RayCaster' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Inputs/TouchEventInput' {
  declare module.exports: any;
}

declare module 'ovrui/lib/OVRUI' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Player/Glyphs' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Player/OculusPlayer' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Player/Overlay' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Player/Player' {
  declare module.exports: any;
}

declare module 'ovrui/lib/Player/setStyles' {
  declare module.exports: any;
}

declare module 'ovrui/lib/SDFFont/DefaultFont' {
  declare module.exports: any;
}

declare module 'ovrui/lib/SDFFont/SDFFont' {
  declare module.exports: any;
}

declare module 'ovrui/lib/ThreeShim' {
  declare module.exports: any;
}

declare module 'ovrui/lib/UIView/GuiSys' {
  declare module.exports: any;
}

declare module 'ovrui/lib/UIView/GuiSysEvent' {
  declare module.exports: any;
}

declare module 'ovrui/lib/UIView/UIView' {
  declare module.exports: any;
}

declare module 'ovrui/lib/UIView/UIViewUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ovrui/dist/ovrui.js' {
  declare module.exports: $Exports<'ovrui/dist/ovrui'>;
}
declare module 'ovrui/dist/ovrui.min.js' {
  declare module.exports: $Exports<'ovrui/dist/ovrui.min'>;
}
declare module 'ovrui/index' {
  declare module.exports: $Exports<'ovrui'>;
}
declare module 'ovrui/index.js' {
  declare module.exports: $Exports<'ovrui'>;
}
declare module 'ovrui/lib/Control/AppControls.js' {
  declare module.exports: $Exports<'ovrui/lib/Control/AppControls'>;
}
declare module 'ovrui/lib/Control/DeviceOrientationControls.js' {
  declare module.exports: $Exports<'ovrui/lib/Control/DeviceOrientationControls'>;
}
declare module 'ovrui/lib/Control/MousePanControls.js' {
  declare module.exports: $Exports<'ovrui/lib/Control/MousePanControls'>;
}
declare module 'ovrui/lib/Control/VRControls.js' {
  declare module.exports: $Exports<'ovrui/lib/Control/VRControls'>;
}
declare module 'ovrui/lib/Control/VREffect.js' {
  declare module.exports: $Exports<'ovrui/lib/Control/VREffect'>;
}
declare module 'ovrui/lib/FourByFourRect/VectorGeometry.js' {
  declare module.exports: $Exports<'ovrui/lib/FourByFourRect/VectorGeometry'>;
}
declare module 'ovrui/lib/Inputs/__tests__/GamepadEventInput-test.js' {
  declare module.exports: $Exports<'ovrui/lib/Inputs/__tests__/GamepadEventInput-test'>;
}
declare module 'ovrui/lib/Inputs/EventInput.js' {
  declare module.exports: $Exports<'ovrui/lib/Inputs/EventInput'>;
}
declare module 'ovrui/lib/Inputs/GamepadEventInput.js' {
  declare module.exports: $Exports<'ovrui/lib/Inputs/GamepadEventInput'>;
}
declare module 'ovrui/lib/Inputs/KeyboardEventInput.js' {
  declare module.exports: $Exports<'ovrui/lib/Inputs/KeyboardEventInput'>;
}
declare module 'ovrui/lib/Inputs/MouseEventInput.js' {
  declare module.exports: $Exports<'ovrui/lib/Inputs/MouseEventInput'>;
}
declare module 'ovrui/lib/Inputs/MouseRayCaster.js' {
  declare module.exports: $Exports<'ovrui/lib/Inputs/MouseRayCaster'>;
}
declare module 'ovrui/lib/Inputs/RayCaster.js' {
  declare module.exports: $Exports<'ovrui/lib/Inputs/RayCaster'>;
}
declare module 'ovrui/lib/Inputs/TouchEventInput.js' {
  declare module.exports: $Exports<'ovrui/lib/Inputs/TouchEventInput'>;
}
declare module 'ovrui/lib/OVRUI.js' {
  declare module.exports: $Exports<'ovrui/lib/OVRUI'>;
}
declare module 'ovrui/lib/Player/Glyphs.js' {
  declare module.exports: $Exports<'ovrui/lib/Player/Glyphs'>;
}
declare module 'ovrui/lib/Player/OculusPlayer.js' {
  declare module.exports: $Exports<'ovrui/lib/Player/OculusPlayer'>;
}
declare module 'ovrui/lib/Player/Overlay.js' {
  declare module.exports: $Exports<'ovrui/lib/Player/Overlay'>;
}
declare module 'ovrui/lib/Player/Player.js' {
  declare module.exports: $Exports<'ovrui/lib/Player/Player'>;
}
declare module 'ovrui/lib/Player/setStyles.js' {
  declare module.exports: $Exports<'ovrui/lib/Player/setStyles'>;
}
declare module 'ovrui/lib/SDFFont/DefaultFont.js' {
  declare module.exports: $Exports<'ovrui/lib/SDFFont/DefaultFont'>;
}
declare module 'ovrui/lib/SDFFont/SDFFont.js' {
  declare module.exports: $Exports<'ovrui/lib/SDFFont/SDFFont'>;
}
declare module 'ovrui/lib/ThreeShim.js' {
  declare module.exports: $Exports<'ovrui/lib/ThreeShim'>;
}
declare module 'ovrui/lib/UIView/GuiSys.js' {
  declare module.exports: $Exports<'ovrui/lib/UIView/GuiSys'>;
}
declare module 'ovrui/lib/UIView/GuiSysEvent.js' {
  declare module.exports: $Exports<'ovrui/lib/UIView/GuiSysEvent'>;
}
declare module 'ovrui/lib/UIView/UIView.js' {
  declare module.exports: $Exports<'ovrui/lib/UIView/UIView'>;
}
declare module 'ovrui/lib/UIView/UIViewUtil.js' {
  declare module.exports: $Exports<'ovrui/lib/UIView/UIViewUtil'>;
}
