// flow-typed signature: b4f37d8844500cc31441a135c46e4ae4
// flow-typed version: <<STUB>>/react-vr-web_v~1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-vr-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-vr-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-vr-web/js/Audio/AudioTypes' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Audio/getSupportedFormats' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Audio/OVRAudio' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Audio/VRAudioBufferManager' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Audio/VRAudioBufferSource' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Audio/VRAudioComponent' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Audio/VRAudioContext' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/bundleFromRoot' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/createRootView' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/defs/ovrui' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/defs/react-vr' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/defs/three' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Events/MediaEvent' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/MTLParser-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJGroup-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJLoader-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJParser-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/MTLLoader' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/MTLParser' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/OBJGroup' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/OBJLoader' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/OBJParser' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Loaders/WavefrontOBJ/OBJTypes' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/__tests__/Module-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/AndroidConstants' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/AsyncLocalStorage' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/ControllerInfo' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/ExternalAssets' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/GlyphTextures' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/History' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/LinkingManager' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/Location' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/Module' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/Networking' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/RCTAudioModule' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/RCTExceptionsManager' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/RCTSourceCode' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/RCTVideoModule' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/ReactVRConstants' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/Timing' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/UIManager' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Modules/WebSocketModule' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/ReactNativeContext' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/RNBridge' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/__tests__/merge-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/__tests__/RefCountCache-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/CubePano' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/extractURL' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/fetchResource' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/HPano' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/isPositive' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/merge' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/RCTBindedResource' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/RCTHeadModel' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/RCTInputControls' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/RCTResourceManager' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/RCTVideoPlayer' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/RefCountCache' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Utils/Yoga.bundle' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Video/BasicVideoPlayer' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Video/getSupportedFormats' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Video/OVRVideo' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Video/VRVideoComponent' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Video/VRVideoPlayer' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/__tests__/BaseView-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/__tests__/Image-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/__tests__/Model-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/__tests__/Text-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/__tests__/View-test' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/AmbientLight' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/BaseMesh' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/BaseView' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Box' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Cylinder' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/CylindricalPanel' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/DirectionalLight' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Image' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Model' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Pano' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Plane' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/PointLight' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Prefetch' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/RawText' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Scene' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Sound' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Sphere' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/SpotLight' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Text' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/Video' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/VideoPano' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/Views/View' {
  declare module.exports: any;
}

declare module 'react-vr-web/js/VRInstance' {
  declare module.exports: any;
}

declare module 'react-vr-web/ReactVR' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-vr-web/js/Audio/AudioTypes.js' {
  declare module.exports: $Exports<'react-vr-web/js/Audio/AudioTypes'>;
}
declare module 'react-vr-web/js/Audio/getSupportedFormats.js' {
  declare module.exports: $Exports<'react-vr-web/js/Audio/getSupportedFormats'>;
}
declare module 'react-vr-web/js/Audio/OVRAudio.js' {
  declare module.exports: $Exports<'react-vr-web/js/Audio/OVRAudio'>;
}
declare module 'react-vr-web/js/Audio/VRAudioBufferManager.js' {
  declare module.exports: $Exports<'react-vr-web/js/Audio/VRAudioBufferManager'>;
}
declare module 'react-vr-web/js/Audio/VRAudioBufferSource.js' {
  declare module.exports: $Exports<'react-vr-web/js/Audio/VRAudioBufferSource'>;
}
declare module 'react-vr-web/js/Audio/VRAudioComponent.js' {
  declare module.exports: $Exports<'react-vr-web/js/Audio/VRAudioComponent'>;
}
declare module 'react-vr-web/js/Audio/VRAudioContext.js' {
  declare module.exports: $Exports<'react-vr-web/js/Audio/VRAudioContext'>;
}
declare module 'react-vr-web/js/bundleFromRoot.js' {
  declare module.exports: $Exports<'react-vr-web/js/bundleFromRoot'>;
}
declare module 'react-vr-web/js/createRootView.js' {
  declare module.exports: $Exports<'react-vr-web/js/createRootView'>;
}
declare module 'react-vr-web/js/defs/ovrui.js' {
  declare module.exports: $Exports<'react-vr-web/js/defs/ovrui'>;
}
declare module 'react-vr-web/js/defs/react-vr.js' {
  declare module.exports: $Exports<'react-vr-web/js/defs/react-vr'>;
}
declare module 'react-vr-web/js/defs/three.js' {
  declare module.exports: $Exports<'react-vr-web/js/defs/three'>;
}
declare module 'react-vr-web/js/Events/MediaEvent.js' {
  declare module.exports: $Exports<'react-vr-web/js/Events/MediaEvent'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/MTLParser-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/MTLParser-test'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJGroup-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJGroup-test'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJLoader-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJLoader-test'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJParser-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/__tests__/OBJParser-test'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/MTLLoader.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/MTLLoader'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/MTLParser.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/MTLParser'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/OBJGroup.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/OBJGroup'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/OBJLoader.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/OBJLoader'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/OBJParser.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/OBJParser'>;
}
declare module 'react-vr-web/js/Loaders/WavefrontOBJ/OBJTypes.js' {
  declare module.exports: $Exports<'react-vr-web/js/Loaders/WavefrontOBJ/OBJTypes'>;
}
declare module 'react-vr-web/js/Modules/__tests__/Module-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/__tests__/Module-test'>;
}
declare module 'react-vr-web/js/Modules/AndroidConstants.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/AndroidConstants'>;
}
declare module 'react-vr-web/js/Modules/AsyncLocalStorage.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/AsyncLocalStorage'>;
}
declare module 'react-vr-web/js/Modules/ControllerInfo.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/ControllerInfo'>;
}
declare module 'react-vr-web/js/Modules/ExternalAssets.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/ExternalAssets'>;
}
declare module 'react-vr-web/js/Modules/GlyphTextures.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/GlyphTextures'>;
}
declare module 'react-vr-web/js/Modules/History.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/History'>;
}
declare module 'react-vr-web/js/Modules/LinkingManager.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/LinkingManager'>;
}
declare module 'react-vr-web/js/Modules/Location.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/Location'>;
}
declare module 'react-vr-web/js/Modules/Module.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/Module'>;
}
declare module 'react-vr-web/js/Modules/Networking.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/Networking'>;
}
declare module 'react-vr-web/js/Modules/RCTAudioModule.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/RCTAudioModule'>;
}
declare module 'react-vr-web/js/Modules/RCTExceptionsManager.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/RCTExceptionsManager'>;
}
declare module 'react-vr-web/js/Modules/RCTSourceCode.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/RCTSourceCode'>;
}
declare module 'react-vr-web/js/Modules/RCTVideoModule.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/RCTVideoModule'>;
}
declare module 'react-vr-web/js/Modules/ReactVRConstants.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/ReactVRConstants'>;
}
declare module 'react-vr-web/js/Modules/Timing.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/Timing'>;
}
declare module 'react-vr-web/js/Modules/UIManager.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/UIManager'>;
}
declare module 'react-vr-web/js/Modules/WebSocketModule.js' {
  declare module.exports: $Exports<'react-vr-web/js/Modules/WebSocketModule'>;
}
declare module 'react-vr-web/js/ReactNativeContext.js' {
  declare module.exports: $Exports<'react-vr-web/js/ReactNativeContext'>;
}
declare module 'react-vr-web/js/RNBridge.js' {
  declare module.exports: $Exports<'react-vr-web/js/RNBridge'>;
}
declare module 'react-vr-web/js/Utils/__tests__/merge-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/__tests__/merge-test'>;
}
declare module 'react-vr-web/js/Utils/__tests__/RefCountCache-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/__tests__/RefCountCache-test'>;
}
declare module 'react-vr-web/js/Utils/CubePano.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/CubePano'>;
}
declare module 'react-vr-web/js/Utils/extractURL.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/extractURL'>;
}
declare module 'react-vr-web/js/Utils/fetchResource.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/fetchResource'>;
}
declare module 'react-vr-web/js/Utils/HPano.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/HPano'>;
}
declare module 'react-vr-web/js/Utils/isPositive.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/isPositive'>;
}
declare module 'react-vr-web/js/Utils/merge.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/merge'>;
}
declare module 'react-vr-web/js/Utils/RCTBindedResource.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/RCTBindedResource'>;
}
declare module 'react-vr-web/js/Utils/RCTHeadModel.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/RCTHeadModel'>;
}
declare module 'react-vr-web/js/Utils/RCTInputControls.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/RCTInputControls'>;
}
declare module 'react-vr-web/js/Utils/RCTResourceManager.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/RCTResourceManager'>;
}
declare module 'react-vr-web/js/Utils/RCTVideoPlayer.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/RCTVideoPlayer'>;
}
declare module 'react-vr-web/js/Utils/RefCountCache.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/RefCountCache'>;
}
declare module 'react-vr-web/js/Utils/Yoga.bundle.js' {
  declare module.exports: $Exports<'react-vr-web/js/Utils/Yoga.bundle'>;
}
declare module 'react-vr-web/js/Video/BasicVideoPlayer.js' {
  declare module.exports: $Exports<'react-vr-web/js/Video/BasicVideoPlayer'>;
}
declare module 'react-vr-web/js/Video/getSupportedFormats.js' {
  declare module.exports: $Exports<'react-vr-web/js/Video/getSupportedFormats'>;
}
declare module 'react-vr-web/js/Video/OVRVideo.js' {
  declare module.exports: $Exports<'react-vr-web/js/Video/OVRVideo'>;
}
declare module 'react-vr-web/js/Video/VRVideoComponent.js' {
  declare module.exports: $Exports<'react-vr-web/js/Video/VRVideoComponent'>;
}
declare module 'react-vr-web/js/Video/VRVideoPlayer.js' {
  declare module.exports: $Exports<'react-vr-web/js/Video/VRVideoPlayer'>;
}
declare module 'react-vr-web/js/Views/__tests__/BaseView-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/__tests__/BaseView-test'>;
}
declare module 'react-vr-web/js/Views/__tests__/Image-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/__tests__/Image-test'>;
}
declare module 'react-vr-web/js/Views/__tests__/Model-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/__tests__/Model-test'>;
}
declare module 'react-vr-web/js/Views/__tests__/Text-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/__tests__/Text-test'>;
}
declare module 'react-vr-web/js/Views/__tests__/View-test.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/__tests__/View-test'>;
}
declare module 'react-vr-web/js/Views/AmbientLight.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/AmbientLight'>;
}
declare module 'react-vr-web/js/Views/BaseMesh.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/BaseMesh'>;
}
declare module 'react-vr-web/js/Views/BaseView.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/BaseView'>;
}
declare module 'react-vr-web/js/Views/Box.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Box'>;
}
declare module 'react-vr-web/js/Views/Cylinder.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Cylinder'>;
}
declare module 'react-vr-web/js/Views/CylindricalPanel.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/CylindricalPanel'>;
}
declare module 'react-vr-web/js/Views/DirectionalLight.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/DirectionalLight'>;
}
declare module 'react-vr-web/js/Views/Image.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Image'>;
}
declare module 'react-vr-web/js/Views/Model.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Model'>;
}
declare module 'react-vr-web/js/Views/Pano.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Pano'>;
}
declare module 'react-vr-web/js/Views/Plane.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Plane'>;
}
declare module 'react-vr-web/js/Views/PointLight.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/PointLight'>;
}
declare module 'react-vr-web/js/Views/Prefetch.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Prefetch'>;
}
declare module 'react-vr-web/js/Views/RawText.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/RawText'>;
}
declare module 'react-vr-web/js/Views/Scene.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Scene'>;
}
declare module 'react-vr-web/js/Views/Sound.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Sound'>;
}
declare module 'react-vr-web/js/Views/Sphere.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Sphere'>;
}
declare module 'react-vr-web/js/Views/SpotLight.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/SpotLight'>;
}
declare module 'react-vr-web/js/Views/Text.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Text'>;
}
declare module 'react-vr-web/js/Views/Video.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/Video'>;
}
declare module 'react-vr-web/js/Views/VideoPano.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/VideoPano'>;
}
declare module 'react-vr-web/js/Views/View.js' {
  declare module.exports: $Exports<'react-vr-web/js/Views/View'>;
}
declare module 'react-vr-web/js/VRInstance.js' {
  declare module.exports: $Exports<'react-vr-web/js/VRInstance'>;
}
declare module 'react-vr-web/ReactVR.js' {
  declare module.exports: $Exports<'react-vr-web/ReactVR'>;
}
