// flow-typed signature: d9b43797c6d877704d56b299f70354d0
// flow-typed version: <<STUB>>/react-vr_v1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-vr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-vr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-vr/jest/setup' {
  declare module.exports: any;
}

declare module 'react-vr/lib-assets/VideoControlGlyphs' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Components/View/View.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Lights/AmbientLight' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Lights/DirectionalLight' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Lights/PointLight' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Lights/SpotLight' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Mesh/Box' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Mesh/Cylinder' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Mesh/Model' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Mesh/Plane' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Mesh/Sphere' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Pano/Pano' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Pano/Prefetch' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/react-vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Scene/Scene' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Sound/Sound' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/StyleSheet/LayoutAndTransformColorPropTypes' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/StyleSheet/LayoutAndTransformOpacityPropTypes' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/StyleSheet/LayoutAndTransformPropTypes' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/StyleSheet/LayoutAndTransformTintPropTypes' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/StyleSheet/LayoutPropTypes.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Utilities/asset' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Utilities/createGlyph' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Utilities/Platform.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Utilities/VrHeadModel' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Utilities/VrMath' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Utilities/VrSoundEffects' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Video/MediaPlayerState' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Video/Video' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Video/VideoControl' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/Video/VideoUtils' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VideoPano/VideoPano' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VrAnimated/VrAnimated' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VrButton/VrButton' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRLayers/CylindricalPanel' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/AnimatedImplementation.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/BackAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/HMRLoadingView.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/Image.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/NetworkOverlay.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DatePickerAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DatePickerIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DrawerLayoutAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigationExperimental.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigatorBreadcrumbNavigationBarStyles.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigatorIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/PickerAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/PickerIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ProgressBarAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ProgressViewIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/RecyclerViewBackedScrollview.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/SegmentedControlIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/SnapshotViewIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/StatusBarIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TabBarIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TimePickerAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ToastAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ToolbarAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TouchableNativeFeedback.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/VibrationIOS.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ViewPagerAndroid.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/WebView.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/processTransform.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/RCTNetworking.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/ReactNativeViewAttributes.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/Settings.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/setupDevtools.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/Text.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/TransformPropTypes.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/TVEventHandler.vr' {
  declare module.exports: any;
}

declare module 'react-vr/Libraries/VRReactOverrides/YellowBox.vr' {
  declare module.exports: any;
}

declare module 'react-vr/scripts/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-vr/jest/setup.js' {
  declare module.exports: $Exports<'react-vr/jest/setup'>;
}
declare module 'react-vr/lib-assets/VideoControlGlyphs.js' {
  declare module.exports: $Exports<'react-vr/lib-assets/VideoControlGlyphs'>;
}
declare module 'react-vr/Libraries/Components/View/View.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Components/View/View.vr'>;
}
declare module 'react-vr/Libraries/Lights/AmbientLight.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Lights/AmbientLight'>;
}
declare module 'react-vr/Libraries/Lights/DirectionalLight.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Lights/DirectionalLight'>;
}
declare module 'react-vr/Libraries/Lights/PointLight.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Lights/PointLight'>;
}
declare module 'react-vr/Libraries/Lights/SpotLight.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Lights/SpotLight'>;
}
declare module 'react-vr/Libraries/Mesh/Box.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Mesh/Box'>;
}
declare module 'react-vr/Libraries/Mesh/Cylinder.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Mesh/Cylinder'>;
}
declare module 'react-vr/Libraries/Mesh/Model.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Mesh/Model'>;
}
declare module 'react-vr/Libraries/Mesh/Plane.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Mesh/Plane'>;
}
declare module 'react-vr/Libraries/Mesh/Sphere.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Mesh/Sphere'>;
}
declare module 'react-vr/Libraries/Pano/Pano.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Pano/Pano'>;
}
declare module 'react-vr/Libraries/Pano/Prefetch.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Pano/Prefetch'>;
}
declare module 'react-vr/Libraries/react-vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/react-vr'>;
}
declare module 'react-vr/Libraries/Scene/Scene.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Scene/Scene'>;
}
declare module 'react-vr/Libraries/Sound/Sound.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Sound/Sound'>;
}
declare module 'react-vr/Libraries/StyleSheet/LayoutAndTransformColorPropTypes.js' {
  declare module.exports: $Exports<'react-vr/Libraries/StyleSheet/LayoutAndTransformColorPropTypes'>;
}
declare module 'react-vr/Libraries/StyleSheet/LayoutAndTransformOpacityPropTypes.js' {
  declare module.exports: $Exports<'react-vr/Libraries/StyleSheet/LayoutAndTransformOpacityPropTypes'>;
}
declare module 'react-vr/Libraries/StyleSheet/LayoutAndTransformPropTypes.js' {
  declare module.exports: $Exports<'react-vr/Libraries/StyleSheet/LayoutAndTransformPropTypes'>;
}
declare module 'react-vr/Libraries/StyleSheet/LayoutAndTransformTintPropTypes.js' {
  declare module.exports: $Exports<'react-vr/Libraries/StyleSheet/LayoutAndTransformTintPropTypes'>;
}
declare module 'react-vr/Libraries/StyleSheet/LayoutPropTypes.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/StyleSheet/LayoutPropTypes.vr'>;
}
declare module 'react-vr/Libraries/Utilities/asset.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Utilities/asset'>;
}
declare module 'react-vr/Libraries/Utilities/createGlyph.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Utilities/createGlyph'>;
}
declare module 'react-vr/Libraries/Utilities/Platform.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Utilities/Platform.vr'>;
}
declare module 'react-vr/Libraries/Utilities/VrHeadModel.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Utilities/VrHeadModel'>;
}
declare module 'react-vr/Libraries/Utilities/VrMath.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Utilities/VrMath'>;
}
declare module 'react-vr/Libraries/Utilities/VrSoundEffects.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Utilities/VrSoundEffects'>;
}
declare module 'react-vr/Libraries/Video/MediaPlayerState.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Video/MediaPlayerState'>;
}
declare module 'react-vr/Libraries/Video/Video.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Video/Video'>;
}
declare module 'react-vr/Libraries/Video/VideoControl.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Video/VideoControl'>;
}
declare module 'react-vr/Libraries/Video/VideoUtils.js' {
  declare module.exports: $Exports<'react-vr/Libraries/Video/VideoUtils'>;
}
declare module 'react-vr/Libraries/VideoPano/VideoPano.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VideoPano/VideoPano'>;
}
declare module 'react-vr/Libraries/VrAnimated/VrAnimated.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VrAnimated/VrAnimated'>;
}
declare module 'react-vr/Libraries/VrButton/VrButton.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VrButton/VrButton'>;
}
declare module 'react-vr/Libraries/VRLayers/CylindricalPanel.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRLayers/CylindricalPanel'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/AnimatedImplementation.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/AnimatedImplementation.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/BackAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/BackAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/HMRLoadingView.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/HMRLoadingView.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/Image.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/Image.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/NetworkOverlay.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/NetworkOverlay.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DatePickerAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DatePickerAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DatePickerIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DatePickerIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DrawerLayoutAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/DrawerLayoutAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigationExperimental.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigationExperimental.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigatorBreadcrumbNavigationBarStyles.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigatorBreadcrumbNavigationBarStyles.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigatorIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/NavigatorIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/PickerAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/PickerAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/PickerIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/PickerIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ProgressBarAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ProgressBarAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ProgressViewIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ProgressViewIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/RecyclerViewBackedScrollview.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/RecyclerViewBackedScrollview.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/SegmentedControlIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/SegmentedControlIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/SnapshotViewIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/SnapshotViewIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/StatusBarIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/StatusBarIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TabBarIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TabBarIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TimePickerAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TimePickerAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ToastAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ToastAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ToolbarAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ToolbarAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TouchableNativeFeedback.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/TouchableNativeFeedback.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/VibrationIOS.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/VibrationIOS.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ViewPagerAndroid.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/ViewPagerAndroid.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/PlatformSpecific/WebView.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/PlatformSpecific/WebView.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/processTransform.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/processTransform.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/RCTNetworking.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/RCTNetworking.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/ReactNativeViewAttributes.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/ReactNativeViewAttributes.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/Settings.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/Settings.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/setupDevtools.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/setupDevtools.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/Text.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/Text.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/TransformPropTypes.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/TransformPropTypes.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/TVEventHandler.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/TVEventHandler.vr'>;
}
declare module 'react-vr/Libraries/VRReactOverrides/YellowBox.vr.js' {
  declare module.exports: $Exports<'react-vr/Libraries/VRReactOverrides/YellowBox.vr'>;
}
declare module 'react-vr/scripts/bundle.js' {
  declare module.exports: $Exports<'react-vr/scripts/bundle'>;
}
