// flow-typed signature: b8f87b8e0928a816b140ce8d3a630a83
// flow-typed version: <<STUB>>/xopen_v1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xopen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xopen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'xopen/index' {
  declare module.exports: $Exports<'xopen'>;
}
declare module 'xopen/index.js' {
  declare module.exports: $Exports<'xopen'>;
}
